/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import flash.display.Sprite;
	
	import test.com.infrared5.application.command.AddUser;
	import test.com.infrared5.application.command.CommandSuite;
	import test.com.infrared5.application.command.GetUsers;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var test_com_infrared5_application_command_GetUsers_obj:test.com.infrared5.application.command.GetUsers;
		
		private var test_com_infrared5_application_command_AddUser_obj:test.com.infrared5.application.command.AddUser;
		private var test_com_infrared5_application_command_CommandSuite_obj:test.com.infrared5.application.command.CommandSuite;
	}
}